os: windows
language: rust
rust: stable
cache: cargo

install:
  - bin/install-python.bat
  - py bin/install-studio.py
  - cargo install run-in-roblox
  - py -3 bin/rbx-studio-sign-in.py $ROBLOXSECURITY

script:
  - echo "Run tests!"
  - run-in-roblox place.rbxlx -s bin/run-tests.lua

branches:
  only:
  - master